logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/H2/KGBook
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto-: false
