CREATE TABLE IF NOT EXISTS BOOK (
  id BIGINT NOT NULL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  author VARCHAR(100) NOT NULL,
  publisher VARCHAR(100) NOT NULL,
  publish_date TIMESTAMP NOT NULL,
  isbn VARCHAR(20) NOT NULL,
  description TEXT
);
