CREATE TABLE IF NOT EXISTS BOOK (
  isbn VARCHAR(20) NOT NULL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  author VARCHAR(100) NOT NULL,
  publisher VARCHAR(100) NOT NULL,
  publish_date TIMESTAMP NOT NULL,
  description TEXT,
  originImageUrl VARCHAR(100),
  s3ImageUrl VARCHAR(100)
);
